use governor::DefaultKeyedRateLimiter;
use governor::Quota;
use log::info;
use log::warn;
use parking_lot::RwLock;
use quinn::RecvStream;
use quinn::SendStream;
use rand::prelude::*;
use std::collections::HashMap;
use std::net::IpAddr;
use std::time::Duration;
use tokio::sync::Notify;
use tokio::sync::mpsc;
use tokio::sync::oneshot;
use tokio::time::Instant;

use crate::names::{Names, hash_key};
use crate::proto::ServerboundControlMessage;

#[derive(Debug)]
pub enum RouterRequest {
    RouteRequest(RouterCallback),
    BroadcastRequest(String),
    ServerboundControlMessage(ServerboundControlMessage),
    TicketRequest(TicketCallback),
}

type RouterCallback = oneshot::Sender<(SendStream, RecvStream)>;
type TicketCallback = oneshot::Sender<Option<String>>;
type RouteRequestReceiver = mpsc::UnboundedSender<RouterRequest>;

#[allow(clippy::module_name_repetitions)]
pub struct RoutingTable {
    table: RwLock<HashMap<String, RouteRequestReceiver>>,
    base_domain: String,
    limiter: DefaultKeyedRateLimiter<IpAddr>,
    names: Names,
    registered: Notify,
    startup_grace: Duration,
}

pub enum RoutingError {
    InvalidDomain,
    RateLimited,
    /// A persistent world that isn't online; it didn't come back within the grace period.
    Starting,
}

#[derive(Debug, thiserror::Error)]
pub enum RegisterError {
    #[error("invalid_key")]
    InvalidKey,
    #[error("name_in_use")]
    NameInUse,
    #[error("internal")]
    Store(#[from] rusqlite::Error),
}

/// World keys are generated by the mod; bound their size since they arrive from anyone.
const KEY_LEN: std::ops::RangeInclusive<usize> = 16..=256;

impl RoutingTable {
    pub fn new(base_domain: String, names: Names, startup_grace: Duration) -> Self {
        RoutingTable {
            table: RwLock::default(),
            base_domain,
            limiter: DefaultKeyedRateLimiter::dashmap(Quota::per_minute(30.try_into().unwrap())),
            names,
            registered: Notify::new(),
            startup_grace,
        }
    }

    /// Whether `domain` belongs to a persistent world (online or not).
    fn is_persistent(&self, domain: &str) -> bool {
        domain
            .strip_suffix(&format!(".{}", self.base_domain))
            .is_some_and(|label| self.names.is_taken(label).unwrap_or(false))
    }

    /// For a persistent world that is offline, e.g. restarting in the background after its
    /// host left: whether it came back online within the grace period.
    async fn wait_for_host(&self, domain: &str) -> bool {
        if !self.is_persistent(domain) {
            return false;
        }
        let deadline = Instant::now() + self.startup_grace;
        loop {
            // Created before the check, so a registration in between still wakes it.
            let registered = self.registered.notified();
            if self.table.read().contains_key(domain) {
                return true;
            }
            if tokio::time::timeout_at(deadline, registered).await.is_err() {
                return false;
            }
        }
    }

    pub fn size(&self) -> usize {
        self.table.read().len()
    }

    pub fn broadcast(&self, message: &str) {
        for sender in self.table.read().values() {
            sender
                .send(RouterRequest::BroadcastRequest(message.to_string()))
                .unwrap();
        }
    }

    pub async fn route_limited(
        &self,
        domain: &str,
        ip: IpAddr,
    ) -> Result<(SendStream, RecvStream), RoutingError> {
        if self.limiter.check_key(&ip.to_canonical()).is_err() {
            return Err(RoutingError::RateLimited);
        }
        self.limiter.retain_recent();
        if !self.table.read().contains_key(domain) {
            if self.wait_for_host(domain).await {
                info!("{} came back online for a waiting player", domain);
            } else if self.is_persistent(domain) {
                return Err(RoutingError::Starting);
            } else {
                return Err(RoutingError::InvalidDomain);
            }
        }
        let (send, recv) = oneshot::channel();
        self.table
            .read()
            .get(domain)
            .ok_or(RoutingError::InvalidDomain)?
            .send(RouterRequest::RouteRequest(send))
            .ok()
            .ok_or(RoutingError::InvalidDomain)?;
        recv.await.ok().ok_or(RoutingError::InvalidDomain)
    }

    /// Whether a status ping should say the world is starting rather than unknown.
    pub fn is_offline_persistent(&self, domain: &str) -> bool {
        !self.table.read().contains_key(domain) && self.is_persistent(domain)
    }

    fn domain(&self, label: &str) -> String {
        crate::unicode_madness::validate_and_normalize_domain(&format!(
            "{label}.{}",
            self.base_domain
        ))
        .expect("Resulting domain is not valid")
    }

    /// A label that is neither live nor reserved by some world's key.
    fn fresh_label(
        &self,
        live: &HashMap<String, RouteRequestReceiver>,
    ) -> Result<String, RegisterError> {
        loop {
            let label = format!(
                "{}-{}",
                crate::wordlist::ID_WORDS.choose(&mut rand::rng()).unwrap(),
                crate::wordlist::ID_WORDS.choose(&mut rand::rng()).unwrap(),
            );
            if !live.contains_key(&self.domain(&label)) && !self.names.is_taken(&label)? {
                return Ok(label);
            }
            warn!("Randomly selected label {} conflicts; trying again", label);
        }
    }

    /// With a world key, the world gets the same name every time; without one, a
    /// fresh random name as in e4mc. One live session per name.
    pub fn register(
        &self,
        key: Option<&str>,
    ) -> Result<(RoutingHandle<'_>, RouteRequestReceiver), RegisterError> {
        let mut lock = self.table.write();
        self.names
            .expire(|label| lock.contains_key(&self.domain(label)))?;
        let label = match key {
            None => self.fresh_label(&lock)?,
            Some(key) if !KEY_LEN.contains(&key.len()) => return Err(RegisterError::InvalidKey),
            Some(key) => {
                let key_hash = hash_key(key);
                if let Some(label) = self.names.label_for(&key_hash)? {
                    if lock.contains_key(&self.domain(&label)) {
                        return Err(RegisterError::NameInUse);
                    }
                    self.names.touch(&label)?;
                    label
                } else {
                    let label = self.fresh_label(&lock)?;
                    self.names.insert(&key_hash, &label)?;
                    label
                }
            }
        };
        let domain = self.domain(&label);
        let (send, recv) = mpsc::unbounded_channel();
        lock.insert(domain.clone(), send.clone());
        self.registered.notify_waiters();
        Ok((
            RoutingHandle {
                recv,
                own: send.downgrade(),
                domain,
                label,
                parent: self,
            },
            send,
        ))
    }

    pub async fn check_ticket(&self, domain: &str, ip: IpAddr) -> Option<String> {
        if self.limiter.check_key(&ip.to_canonical()).is_err() {
            return None;
        }
        self.limiter.retain_recent();
        let (send, recv) = oneshot::channel();
        self.table
            .read()
            .get(domain)?
            .send(RouterRequest::TicketRequest(send))
            .ok()?;
        recv.await.ok()?
    }
}

#[allow(clippy::module_name_repetitions)]
pub struct RoutingHandle<'a> {
    recv: mpsc::UnboundedReceiver<RouterRequest>,
    /// Identifies this session's entry, which a later session may have replaced.
    own: mpsc::WeakUnboundedSender<RouterRequest>,
    domain: String,
    label: String,
    parent: &'a RoutingTable,
}

impl RoutingHandle<'_> {
    pub async fn next(&mut self) -> Option<RouterRequest> {
        self.recv.recv().await
    }

    pub fn domain(&self) -> &str {
        &self.domain
    }

    /// Stops routing new players here, e.g. while the host hands its world to its
    /// background server, which can then take the name. Current players stay connected.
    pub fn detach(&self) {
        let mut table = self.parent.table.write();
        let ours = match (table.get(&self.domain), self.own.upgrade()) {
            (Some(entry), Some(own)) => entry.same_channel(&own),
            _ => false,
        };
        if ours {
            table.remove(&self.domain);
        }
    }
}

impl Drop for RoutingHandle<'_> {
    fn drop(&mut self) {
        info!("Removing stale entry for {}", self.domain);
        self.detach();
        // Keyless names aren't stored, so this is a no-op for them.
        if let Err(e) = self.parent.names.touch(&self.label) {
            warn!("Failed to record last use of {}: {}", self.domain, e);
        }
    }
}
