use governor::DefaultKeyedRateLimiter;
use governor::Quota;
use log::info;
use log::warn;
use parking_lot::RwLock;
use quinn::RecvStream;
use quinn::SendStream;
use rand::prelude::*;
use std::collections::HashMap;
use std::net::IpAddr;
use tokio::sync::mpsc;
use tokio::sync::oneshot;

use crate::names::{Names, hash_key};
use crate::proto::ServerboundControlMessage;

#[derive(Debug)]
pub enum RouterRequest {
    RouteRequest(RouterCallback),
    BroadcastRequest(String),
    ServerboundControlMessage(ServerboundControlMessage),
    TicketRequest(TicketCallback),
}

type RouterCallback = oneshot::Sender<(SendStream, RecvStream)>;
type TicketCallback = oneshot::Sender<Option<String>>;
type RouteRequestReceiver = mpsc::UnboundedSender<RouterRequest>;

#[allow(clippy::module_name_repetitions)]
pub struct RoutingTable {
    table: RwLock<HashMap<String, RouteRequestReceiver>>,
    base_domain: String,
    limiter: DefaultKeyedRateLimiter<IpAddr>,
    names: Names,
}

pub enum RoutingError {
    InvalidDomain,
    RateLimited,
}

#[derive(Debug, thiserror::Error)]
pub enum RegisterError {
    #[error("invalid_key")]
    InvalidKey,
    #[error("name_in_use")]
    NameInUse,
    #[error("internal")]
    Store(#[from] rusqlite::Error),
}

/// World keys are generated by the mod; bound their size since they arrive from anyone.
const KEY_LEN: std::ops::RangeInclusive<usize> = 16..=256;

impl RoutingTable {
    pub fn new(base_domain: String, names: Names) -> Self {
        RoutingTable {
            table: RwLock::default(),
            base_domain,
            limiter: DefaultKeyedRateLimiter::dashmap(Quota::per_minute(30.try_into().unwrap())),
            names,
        }
    }

    pub fn size(&self) -> usize {
        self.table.read().len()
    }

    pub fn broadcast(&self, message: &str) {
        for sender in self.table.read().values() {
            sender
                .send(RouterRequest::BroadcastRequest(message.to_string()))
                .unwrap();
        }
    }

    pub async fn route_limited(
        &self,
        domain: &str,
        ip: IpAddr,
    ) -> Result<(SendStream, RecvStream), RoutingError> {
        if self.limiter.check_key(&ip.to_canonical()).is_err() {
            return Err(RoutingError::RateLimited);
        }
        self.limiter.retain_recent();
        let (send, recv) = oneshot::channel();
        self.table
            .read()
            .get(domain)
            .ok_or(RoutingError::InvalidDomain)?
            .send(RouterRequest::RouteRequest(send))
            .ok()
            .ok_or(RoutingError::InvalidDomain)?;
        recv.await.ok().ok_or(RoutingError::InvalidDomain)
    }

    fn domain(&self, label: &str) -> String {
        crate::unicode_madness::validate_and_normalize_domain(&format!(
            "{label}.{}",
            self.base_domain
        ))
        .expect("Resulting domain is not valid")
    }

    /// A label that is neither live nor reserved by some world's key.
    fn fresh_label(
        &self,
        live: &HashMap<String, RouteRequestReceiver>,
    ) -> Result<String, RegisterError> {
        loop {
            let label = format!(
                "{}-{}",
                crate::wordlist::ID_WORDS.choose(&mut rand::rng()).unwrap(),
                crate::wordlist::ID_WORDS.choose(&mut rand::rng()).unwrap(),
            );
            if !live.contains_key(&self.domain(&label)) && !self.names.is_taken(&label)? {
                return Ok(label);
            }
            warn!("Randomly selected label {} conflicts; trying again", label);
        }
    }

    /// With a world key, the world gets the same name every time; without one, a
    /// fresh random name as in e4mc. One live session per name.
    pub fn register(
        &self,
        key: Option<&str>,
    ) -> Result<(RoutingHandle<'_>, RouteRequestReceiver), RegisterError> {
        let mut lock = self.table.write();
        let label = match key {
            None => self.fresh_label(&lock)?,
            Some(key) if !KEY_LEN.contains(&key.len()) => return Err(RegisterError::InvalidKey),
            Some(key) => {
                let key_hash = hash_key(key);
                if let Some(label) = self.names.label_for(&key_hash)? {
                    if lock.contains_key(&self.domain(&label)) {
                        return Err(RegisterError::NameInUse);
                    }
                    self.names.touch(&label)?;
                    label
                } else {
                    let label = self.fresh_label(&lock)?;
                    self.names.insert(&key_hash, &label)?;
                    label
                }
            }
        };
        let domain = self.domain(&label);
        let (send, recv) = mpsc::unbounded_channel();
        lock.insert(domain.clone(), send.clone());
        Ok((
            RoutingHandle {
                recv,
                domain,
                label,
                parent: self,
            },
            send,
        ))
    }

    pub async fn check_ticket(&self, domain: &str, ip: IpAddr) -> Option<String> {
        if self.limiter.check_key(&ip.to_canonical()).is_err() {
            return None;
        }
        self.limiter.retain_recent();
        let (send, recv) = oneshot::channel();
        self.table
            .read()
            .get(domain)?
            .send(RouterRequest::TicketRequest(send))
            .ok()?;
        recv.await.ok()?
    }
}

#[allow(clippy::module_name_repetitions)]
pub struct RoutingHandle<'a> {
    recv: mpsc::UnboundedReceiver<RouterRequest>,
    domain: String,
    label: String,
    parent: &'a RoutingTable,
}

impl RoutingHandle<'_> {
    pub async fn next(&mut self) -> Option<RouterRequest> {
        self.recv.recv().await
    }

    pub fn domain(&self) -> &str {
        &self.domain
    }
}

impl Drop for RoutingHandle<'_> {
    fn drop(&mut self) {
        info!("Removing stale entry for {}", self.domain);
        self.parent.table.write().remove(&self.domain);
        // Keyless names aren't stored, so this is a no-op for them.
        if let Err(e) = self.parent.names.touch(&self.label) {
            warn!("Failed to record last use of {}: {}", self.domain, e);
        }
    }
}
